REVOKE ALL PRIVILEGES ON SCHEMA lars_poc FROM lars_poc;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA lars_poc FROM lars_poc;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA lars_poc FROM lars_poc;
DROP USER lars_poc;

DROP SCHEMA IF EXISTS lars_poc CASCADE;
